[package]
authors = ["SchweGELBin <schwegelbin@gmail.com>"]
edition = "2024"
name = "smoos-bot"
version = "0.1.0"

[dependencies]
poise = "^0.6"
serde_json = "^1.0"
tokio = { version = "^1.45", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "^0.3"
